[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
